language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: travis.sh
services:
  - postgresql
before_script:
  - psql -c 'create database twocar_stage;' -U postgres
  - cp travis_settings.py config/stage_settings.py
